$(document).ready(function(){
	$(".1").click(function(){
	$('.div1').fadeToggle();
	});
	$(".2").click(function(){
	$('.div2').fadeToggle();
	});
	$(".3").click(function(){
	$('.div3').fadeToggle();
	});
	$(".4").click(function(){
	$('.div4').fadeToggle();
	});
	$(".5").click(function(){
	$('.div5').fadeToggle();
	});
	$(".6").click(function(){
	$('.div6').fadeToggle();
	});
	$(".7").click(function(){
	$('.div7').fadeToggle();
	});
	$(".8").click(function(){
	$('.div8').fadeToggle();
	});
	

});

function formatangka(objek) {
   a = objek.value;
   b = a.replace(/[^\d]/g,"");
   c = "";
   panjang = b.length;
   j = 0;
   for (i = panjang; i > 0; i--) {
     j = j + 1;
     if (((j % 3) == 1) && (j != 1)) {
       c = b.substr(i-1,1) + "." + c;
     } else {
       c = b.substr(i-1,1) + c;
     }
   }
   objek.value = c;
}

function showDiv(select){
   if(select.value=="Alga"){
    document.getElementById('alga').style.display = "block";
	 document.getElementById('sp').style.display = "none";
	   document.getElementById('cm').style.display = "none";
	   document.getElementById('Florence').style.display = "none";
	   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	 document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
   }else if(select.value=="Spring Air"){
    document.getElementById('alga').style.display = "none";
    document.getElementById('sp').style.display = "block";
	  document.getElementById('cm').style.display = "none";
	  document.getElementById('Florence').style.display = "none";
	  document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	    document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
   }else if(select.value=="Bigland"){
    document.getElementById('alga').style.display = "none";
    document.getElementById('sp').style.display = "none";
	  document.getElementById('cm').style.display = "none";
	  document.getElementById('Florence').style.display = "none";
	  document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	    document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "block";
   }else if(select.value=='Comforta'){
	   document.getElementById('alga').style.display = "none";
    document.getElementById('sp').style.display = "none";
    document.getElementById('cm').style.display = "block";
	document.getElementById('Florence').style.display = "none";
	document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	    document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
   }else if(select.value=='Florence'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='block';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	    document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Serta'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "block";
	   document.getElementById('kk').style.display = "none";
	 document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
		document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='King Koil'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "block";
	   document.getElementById('al').style.display = "none";
	 document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Airland'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "block";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Cosisoft'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "block";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Dreamline'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "block";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Dunlopillo'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	document.getElementById('kk').style.display = "none";
	document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	document.getElementById('dun').style.display = "block";
	 document.getElementById('cos').style.display = "none";
	 document.getElementById('lady').style.display = "none";
	 document.getElementById('eli').style.display = "none";
	 document.getElementById('rom').style.display = "none";
	 document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Elite'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "block";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Lady Americana'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "block";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Romance'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	document.getElementById('kk').style.display = "none";
	document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "block";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Therapedic'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	 document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "block";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Theraspine'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('spine').style.display = "block";
	document.getElementById('thera').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Sleep Dream'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "block";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Silent Night'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('silent').style.display = "block";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Superland'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('superland').style.display = "block";
	document.getElementById('bigland').style.display = "none";
	}else if(select.value=='Simmons'){
   document.getElementById('alga').style.display='none';
   document.getElementById('sp').style.display='none';
   document.getElementById('cm').style.display='none';
   document.getElementById('Florence').style.display='none';
   document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	   document.getElementById('al').style.display = "none";
	document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "block";
	document.getElementById('bigland').style.display = "none";
	}else{
	  document.getElementById('alga').style.display = "none";
    document.getElementById('sp').style.display = "none";
    document.getElementById('cm').style.display = "none";
    document.getElementById('Florence').style.display = "none";
	document.getElementById('serta').style.display = "none";
	   document.getElementById('kk').style.display = "none";
	    document.getElementById('al').style.display = "none";
	    document.getElementById('dr').style.display = "none";
	    document.getElementById('cos').style.display = "none";
	document.getElementById('dun').style.display = "none";
	document.getElementById('lady').style.display = "none";
	document.getElementById('eli').style.display = "none";
	document.getElementById('rom').style.display = "none";
	document.getElementById('thera').style.display = "none";
	document.getElementById('spine').style.display = "none";
	document.getElementById('sleep').style.display = "none";
	document.getElementById('silent').style.display = "none";
	document.getElementById('superland').style.display = "none";
	document.getElementById('simmons').style.display = "none";
	document.getElementById('bigland').style.display = "none";
   }
} 


